// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvot3PYu1vYXwgTynN6cYHVLUDItCNUXM',
    appId: '1:1080620342688:web:ee753ae52bd3dea8fd18c5',
    messagingSenderId: '1080620342688',
    projectId: 'valluu-app',
    authDomain: 'valluu-app.firebaseapp.com',
    storageBucket: 'valluu-app.appspot.com',
    measurementId: 'G-H3PEBBWRE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD08TBNx3xUdL1ZF2BTQ3yb0PPgqZy_yYU',
    appId: '1:1080620342688:android:cd07f3262184ba65fd18c5',
    messagingSenderId: '1080620342688',
    projectId: 'valluu-app',
    storageBucket: 'valluu-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRrYaFJohUH5Wx9-e-L3cl8DTtj9WHXAA',
    appId: '1:1080620342688:ios:78349b9474ca3ca6fd18c5',
    messagingSenderId: '1080620342688',
    projectId: 'valluu-app',
    storageBucket: 'valluu-app.appspot.com',
    iosClientId: '1080620342688-nbv8nslt1kr2n9kcrismpj51u3i312sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.valluuApp',
  );
}
